---
services:
  kavita:
    image: lscr.io/linuxserver/kavita:0.8.9
    restart: unless-stopped
    environment:
      PUID: 0
      PGID: 0
      TZ: "Europe/Berlin"
    volumes:
      - ${EXT_PATH}/kavita/config:/config
      - ${EXT_PATH}/media:/media
    ports:
      - 127.0.0.1:${KAVITA_HTTP_PORT:-5001}:5000
    cpus: 1
    labels:
      caddy: kavita.${DOMAIN}
      caddy.import: only_tls
      caddy.reverse_proxy: "127.0.0.1:${KAVITA_HTTP_PORT:-5001}"
      homepage.group: Media
      homepage.name: Kavita
      homepage.icon: kavita
      homepage.href: https://kavita.${DOMAIN}
      homepage.description: E-book and comic reader
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
