services:
  actual_server:
    image: docker.io/actualbudget/actual-server:26.2.0
    restart: unless-stopped
    ports:
      - "127.0.0.1:5006:5006"
    volumes:
      - ${EXT_PATH}/actual:/data
    labels:
      caddy: actual.${DOMAIN}
      caddy.import: sso
      caddy.reverse_proxy: "127.0.0.1:5006"
      homepage.group: Finance
      homepage.name: Actual
      homepage.icon: mdi-cash-multiple
      homepage.href: https://actual.${DOMAIN}
      homepage.description: Budget manager
